/**
 * Script de seed pour les partenaires
 * InsÃ¨re les 45 partenaires mock dans la base de donnÃ©es MongoDB
 * 
 * Usage: npm run seed:partners
 * ou: ts-node src/scripts/seedPartners.ts
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import Partner from '../models/Partner';
import { logger } from '../utils/logger';

// Charger les variables d'environnement
dotenv.config({ path: path.join(__dirname, '../../.env') });

const partnersData = [
  // ========== RESTAURANTS (5) ==========
  {
    name: 'Le Bistrot Gourmand',
    role: 'restaurant',
    specialty: 'Cuisine franÃ§aise traditionnelle',
    location: 'Paris 11e',
    rating: 4.7,
    reviewCount: 342,
    price: '25-45â‚¬',
    availability: 'Ouvert 7j/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=12',
    badges: ['Bio', 'Terrasse', 'Parking'],
    description: 'Restaurant familial proposant une cuisine franÃ§aise authentique avec des produits de saison.',
    ecoFriendly: true,
    skills: ['Cuisine traditionnelle', 'Vins franÃ§ais', 'Accueil chaleureux'],
    experience: '15 ans d\'expÃ©rience',
    email: 'contact@bistrotgourmand.fr',
    phone: '01 43 55 21 89',
    featured: true
  },
  {
    name: 'La Table du Chef',
    role: 'restaurant',
    specialty: 'Gastronomie, 1 Ã‰toile Michelin',
    location: 'Lyon 2e',
    rating: 4.9,
    reviewCount: 567,
    price: '85-120â‚¬',
    availability: 'Mar-Sam midi et soir',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=33',
    badges: ['1 Ã‰toile Michelin', 'Cave exceptionnelle', 'Chef Ã©toilÃ©'],
    description: 'Restaurant gastronomique dirigÃ© par un chef Ã©toilÃ©, cuisine crÃ©ative et raffinÃ©e.',
    ecoFriendly: false,
    skills: ['Haute gastronomie', 'Accords mets-vins', 'Cuisine molÃ©culaire'],
    experience: '25 ans d\'expÃ©rience',
    email: 'reservation@tableduchet.fr',
    phone: '04 78 28 19 59',
    featured: true
  },
  {
    name: 'Sushi Master',
    role: 'restaurant',
    specialty: 'Cuisine japonaise authentique',
    location: 'Marseille 6e',
    rating: 4.6,
    reviewCount: 289,
    price: '30-55â‚¬',
    availability: 'Tous les jours',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=51',
    badges: ['Chef japonais', 'Poisson frais quotidien', 'Menu Omakase'],
    description: 'Restaurant japonais tenu par un chef formÃ© Ã  Tokyo, poissons ultra-frais.',
    ecoFriendly: true,
    skills: ['Sushi', 'Sashimi', 'Cuisine kaiseki'],
    experience: '12 ans d\'expÃ©rience',
    email: 'hello@sushimaster.fr',
    phone: '04 91 33 27 88',
    featured: false
  },
  {
    name: 'Pizza Bella Napoli',
    role: 'restaurant',
    specialty: 'Pizzeria napolitaine',
    location: 'Nice',
    rating: 4.5,
    reviewCount: 423,
    price: '12-22â‚¬',
    availability: 'Midi et soir',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=68',
    badges: ['Four Ã  bois', 'PÃ¢te maison', 'Livraison'],
    description: 'Pizzeria authentique avec four Ã  bois, pÃ¢te pÃ©trie chaque matin.',
    ecoFriendly: false,
    skills: ['Pizza napolitaine', 'Antipasti', 'Desserts italiens'],
    experience: '8 ans d\'expÃ©rience',
    email: 'info@pizzabellanapoli.fr',
    phone: '04 93 87 45 23',
    featured: false
  },
  {
    name: 'Le VÃ©gÃ©tal',
    role: 'restaurant',
    specialty: 'Cuisine vÃ©gÃ©tarienne & vegan',
    location: 'Bordeaux',
    rating: 4.8,
    reviewCount: 198,
    price: '18-32â‚¬',
    availability: 'Lun-Sam midi et soir',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=15',
    badges: ['100% vÃ©gÃ©tal', 'Bio', 'ZÃ©ro dÃ©chet'],
    description: 'Restaurant vÃ©gÃ©talien et bio, engagement zÃ©ro dÃ©chet.',
    ecoFriendly: true,
    skills: ['Cuisine vegan', 'Produits bio', 'PÃ¢tisserie sans gluten'],
    experience: '5 ans d\'expÃ©rience',
    email: 'contact@levegetal.fr',
    phone: '05 56 44 28 91',
    featured: true
  },

  // ========== FOURNISSEURS (5) ==========
  {
    name: 'BioFresh Distribution',
    role: 'fournisseur',
    specialty: 'Fruits et lÃ©gumes bio de saison',
    location: 'Rungis',
    rating: 4.8,
    reviewCount: 156,
    price: 'Sur devis',
    availability: 'Livraison 6j/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=22',
    badges: ['Certification AB', 'Circuit court', 'FraÃ®cheur garantie'],
    description: 'Grossiste en fruits et lÃ©gumes bio, approvisionnement direct producteurs.',
    ecoFriendly: true,
    skills: ['Produits bio', 'Livraison rapide', 'Conseil technique'],
    experience: '20 ans d\'expÃ©rience',
    email: 'commercial@biofresh.fr',
    phone: '01 49 73 24 56',
    featured: true
  },
  {
    name: 'Viandes Premium',
    role: 'fournisseur',
    specialty: 'Viandes Label Rouge et races franÃ§aises',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 234,
    price: 'Sur devis',
    availability: 'Commandes J-1',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=44',
    badges: ['Label Rouge', 'Charolais', 'Limousin'],
    description: 'Grossiste en viandes de qualitÃ©, traÃ§abilitÃ© complÃ¨te de l\'Ã©levage.',
    ecoFriendly: false,
    skills: ['DÃ©coupe professionnelle', 'Maturation', 'Conseil chef'],
    experience: '30 ans d\'expÃ©rience',
    email: 'vente@viandespremium.fr',
    phone: '04 72 85 39 67',
    featured: false
  },
  {
    name: 'Poissonnerie de la CriÃ©e',
    role: 'fournisseur',
    specialty: 'Poissons et fruits de mer ultra-frais',
    location: 'Marseille',
    rating: 4.9,
    reviewCount: 187,
    price: 'Variable selon arrivage',
    availability: 'Arrivage quotidien 6h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=58',
    badges: ['PÃªche locale', 'TraÃ§abilitÃ© MSC', 'Arrivage quotidien'],
    description: 'Poissonnerie professionnelle, approvisionnement criÃ©e locale.',
    ecoFriendly: true,
    skills: ['Poissons mÃ©diterranÃ©e', 'Coquillages', 'Conseils chef'],
    experience: '18 ans d\'expÃ©rience',
    email: 'commande@crieemarseille.fr',
    phone: '04 91 90 12 45',
    featured: true
  },
  {
    name: 'Vins & Spiritueux Prestige',
    role: 'fournisseur',
    specialty: 'Vins fins et spiritueux premium',
    location: 'Bordeaux',
    rating: 4.9,
    reviewCount: 298,
    price: 'Sur devis',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=71',
    badges: ['Grands crus', 'Sommelier conseil', 'Livraison sÃ©curisÃ©e'],
    description: 'Distributeur de vins fins et spiritueux, accompagnement sommelier.',
    ecoFriendly: false,
    skills: ['Å’nologie', 'Grands crus', 'Spiritueux rares'],
    experience: '25 ans d\'expÃ©rience',
    email: 'contact@vinsprestige.fr',
    phone: '05 56 81 23 78',
    featured: true
  },
  {
    name: 'Ã‰picerie Fine du Monde',
    role: 'fournisseur',
    specialty: 'Produits d\'Ã©picerie fine internationaux',
    location: 'Paris 3e',
    rating: 4.6,
    reviewCount: 145,
    price: 'Sur devis',
    availability: '48h dÃ©lai',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=29',
    badges: ['Import direct', '500+ rÃ©fÃ©rences', 'Produits rares'],
    description: 'Grossiste en Ã©picerie fine, huiles, Ã©pices, condiments du monde.',
    ecoFriendly: false,
    skills: ['Ã‰pices rares', 'Huiles d\'exception', 'Condiments artisanaux'],
    experience: '15 ans d\'expÃ©rience',
    email: 'pro@epiceriefine.fr',
    phone: '01 42 77 88 92',
    featured: false
  },

  // ========== ARTISANS (5) ==========
  {
    name: 'Jean-Marc Plomberie',
    role: 'artisan',
    specialty: 'Plomberie, chauffage, climatisation',
    location: 'Paris',
    rating: 4.8,
    reviewCount: 167,
    price: '65â‚¬/h + dÃ©placement',
    availability: 'Urgence 24/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=11',
    badges: ['RGE', 'Urgence 24/7', 'Devis gratuit'],
    description: 'Artisan plombier spÃ©cialisÃ© en restauration commerciale.',
    ecoFriendly: false,
    skills: ['Plomberie pro', 'Lave-vaisselle industriel', 'DÃ©pannage urgent'],
    experience: '22 ans d\'expÃ©rience',
    email: 'jm.plomberie@gmail.com',
    phone: '06 12 34 56 78',
    featured: false
  },
  {
    name: 'Ã‰lectricitÃ© Pro Services',
    role: 'artisan',
    specialty: 'Installation Ã©lectrique professionnelle',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 234,
    price: '55â‚¬/h',
    availability: 'Lun-Sam 8h-19h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=25',
    badges: ['Qualifelec', 'Normes CHR', 'Mise aux normes'],
    description: 'Ã‰lectricien spÃ©cialisÃ© en locaux commerciaux et restauration.',
    ecoFriendly: false,
    skills: ['Ã‰lectricitÃ© commerciale', 'Tableaux Ã©lectriques', 'Mise aux normes'],
    experience: '18 ans d\'expÃ©rience',
    email: 'contact@elec-pro.fr',
    phone: '04 78 45 67 89',
    featured: false
  },
  {
    name: 'Froid Expertise',
    role: 'artisan',
    specialty: 'SpÃ©cialiste froid commercial et climatisation',
    location: 'Marseille',
    rating: 4.9,
    reviewCount: 189,
    price: '75â‚¬/h',
    availability: 'Urgence 24/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=38',
    badges: ['Fluides frigorigÃ¨nes', 'DÃ©pannage urgent', 'Contrat maintenance'],
    description: 'Expert en installation et maintenance de chambres froides.',
    ecoFriendly: true,
    skills: ['Chambres froides', 'Climatisation', 'Contrat maintenance'],
    experience: '25 ans d\'expÃ©rience',
    email: 'urgence@froid-expertise.fr',
    phone: '04 91 22 88 44',
    featured: true
  },
  {
    name: 'Menuiserie Restaurant',
    role: 'artisan',
    specialty: 'AmÃ©nagement et menuiserie sur mesure',
    location: 'Toulouse',
    rating: 4.6,
    reviewCount: 98,
    price: 'Sur devis',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=47',
    badges: ['Bois massif', 'CrÃ©ations sur mesure', 'Finitions haut de gamme'],
    description: 'Menuisier spÃ©cialisÃ© en amÃ©nagement de restaurants.',
    ecoFriendly: true,
    skills: ['Menuiserie sur mesure', 'Agencement', 'Bois nobles'],
    experience: '12 ans d\'expÃ©rience',
    email: 'atelier@menuiserie-resto.fr',
    phone: '05 61 23 45 67',
    featured: false
  },
  {
    name: 'Peinture & DÃ©coration Pro',
    role: 'artisan',
    specialty: 'Peinture et dÃ©coration locaux commerciaux',
    location: 'Nice',
    rating: 4.5,
    reviewCount: 156,
    price: '45â‚¬/h',
    availability: 'Lun-Sam',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=63',
    badges: ['Peintures Ã©cologiques', 'DÃ©coration tendance', 'Devis rapide'],
    description: 'Artisan peintre, spÃ©cialiste rÃ©novation de restaurants.',
    ecoFriendly: true,
    skills: ['Peinture dÃ©corative', 'Enduits', 'RevÃªtements muraux'],
    experience: '10 ans d\'expÃ©rience',
    email: 'contact@peinture-deco.fr',
    phone: '04 93 56 78 90',
    featured: false
  },

  // ========== TRANSPORTEURS (3) ==========
  {
    name: 'Express Livraison Pro',
    role: 'transporteur',
    specialty: 'Livraison express en vÃ©hicules frigorifiques',
    location: 'Paris et ÃŽle-de-France',
    rating: 4.7,
    reviewCount: 432,
    price: 'Ã€ partir de 25â‚¬',
    availability: '7j/7 6h-22h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=18',
    badges: ['VÃ©hicules frigo', 'Tracking temps rÃ©el', 'Livraison J+0'],
    description: 'Service de livraison professionnel pour denrÃ©es pÃ©rissables.',
    ecoFriendly: false,
    skills: ['Transport frigorifique', 'Respect chaÃ®ne du froid', 'Livraison express'],
    experience: '15 ans d\'expÃ©rience',
    email: 'dispatch@express-livraison.fr',
    phone: '01 48 22 33 44',
    featured: true
  },
  {
    name: 'Logistique Food Service',
    role: 'transporteur',
    specialty: 'Transport national denrÃ©es alimentaires',
    location: 'Couverture nationale',
    rating: 4.8,
    reviewCount: 567,
    price: 'Sur devis',
    availability: '24/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=42',
    badges: ['HACCP', 'Flotte 50 vÃ©hicules', 'Assurance marchandises'],
    description: 'Transporteur spÃ©cialisÃ© en logistique alimentaire.',
    ecoFriendly: false,
    skills: ['Transport longue distance', 'Gestion tempÃ©rature', 'Planning optimisÃ©'],
    experience: '28 ans d\'expÃ©rience',
    email: 'commercial@logistique-food.fr',
    phone: '01 60 44 55 66',
    featured: true
  },
  {
    name: 'Coursiers Ã‰cologiques',
    role: 'transporteur',
    specialty: 'Livraison urbaine en vÃ©lo cargo',
    location: 'Paris, Lyon, Marseille',
    rating: 4.6,
    reviewCount: 198,
    price: '15-30â‚¬',
    availability: 'Lun-Sam 7h-20h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=56',
    badges: ['100% vÃ©lo', 'ZÃ©ro Ã©mission', 'Livraison 2h'],
    description: 'Coursiers Ã  vÃ©lo pour livraisons urbaines Ã©co-responsables.',
    ecoFriendly: true,
    skills: ['Livraison vÃ©lo', 'Respect environnement', 'RapiditÃ© urbaine'],
    experience: '5 ans d\'expÃ©rience',
    email: 'hello@coursiers-eco.fr',
    phone: '06 78 90 12 34',
    featured: false
  },

  // ========== COMMUNITY MANAGERS (3) ==========
  {
    name: 'Digital Food Expert',
    role: 'community_manager',
    specialty: 'Community management spÃ©cialisÃ© food',
    location: 'Paris (Remote)',
    rating: 4.9,
    reviewCount: 87,
    price: '550â‚¬/mois',
    availability: 'Contrat 6 mois min',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=31',
    badges: ['Instagram +100K', 'ROI prouvÃ©', 'StratÃ©gie digitale'],
    description: 'Community manager expert en food, croissance Instagram garantie.',
    ecoFriendly: false,
    skills: ['Instagram', 'TikTok', 'StratÃ©gie contenu'],
    experience: '7 ans d\'expÃ©rience',
    email: 'contact@digitalfood.fr',
    phone: '06 45 67 89 01',
    featured: true
  },
  {
    name: 'Content Creator Food',
    role: 'community_manager',
    specialty: 'CrÃ©ation de contenu photo/vidÃ©o food',
    location: 'Lyon (Remote)',
    rating: 4.7,
    reviewCount: 124,
    price: '450â‚¬/mois',
    availability: 'Freelance',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=49',
    badges: ['Photo pro', 'VidÃ©o Reels', 'Storytelling'],
    description: 'CrÃ©ateur de contenu spÃ©cialisÃ© en photographie culinaire.',
    ecoFriendly: false,
    skills: ['Photographie culinaire', 'Montage vidÃ©o', 'Copywriting'],
    experience: '5 ans d\'expÃ©rience',
    email: 'hello@contentcreator.fr',
    phone: '06 23 45 67 89',
    featured: false
  },
  {
    name: 'Social Media Manager Pro',
    role: 'community_manager',
    specialty: 'Gestion complÃ¨te rÃ©seaux sociaux',
    location: 'Remote',
    rating: 4.8,
    reviewCount: 156,
    price: '650â‚¬/mois',
    availability: 'Temps plein',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=64',
    badges: ['Multi-plateformes', 'Analytics', 'PublicitÃ©s Meta'],
    description: 'Social media manager certifiÃ©, gestion complÃ¨te prÃ©sence digitale.',
    ecoFriendly: false,
    skills: ['Meta Ads', 'Google Analytics', 'StratÃ©gie multi-canal'],
    experience: '9 ans d\'expÃ©rience',
    email: 'pro@socialmedia.fr',
    phone: '06 78 12 34 56',
    featured: true
  },

  // ========== BANQUIERS (3) ==========
  {
    name: 'CrÃ©dit Pro Restauration',
    role: 'banquier',
    specialty: 'Financement professionnel CHR',
    location: 'Paris 8e',
    rating: 4.6,
    reviewCount: 234,
    price: 'Consultation gratuite',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=13',
    badges: ['SpÃ©cialiste CHR', 'Taux prÃ©fÃ©rentiels', 'Accompagnement'],
    description: 'Conseiller bancaire spÃ©cialisÃ© en financement restauration.',
    ecoFriendly: false,
    skills: ['CrÃ©dit professionnel', 'Leasing Ã©quipement', 'TrÃ©sorerie'],
    experience: '18 ans d\'expÃ©rience',
    email: 'conseil@creditpro.fr',
    phone: '01 44 55 66 77',
    featured: true
  },
  {
    name: 'Banque des Entrepreneurs',
    role: 'banquier',
    specialty: 'Accompagnement start-up food',
    location: 'Lyon',
    rating: 4.8,
    reviewCount: 167,
    price: 'RDV gratuit',
    availability: 'Lun-Ven 9h-18h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=27',
    badges: ['Start-up friendly', 'PrÃªt d\'honneur', 'MicrocrÃ©dit'],
    description: 'Banque spÃ©cialisÃ©e dans l\'accompagnement de jeunes entrepreneurs.',
    ecoFriendly: true,
    skills: ['Financement innovation', 'PrÃªt BPI', 'Accompagnement'],
    experience: '12 ans d\'expÃ©rience',
    email: 'startup@banque-entrepreneurs.fr',
    phone: '04 72 88 99 00',
    featured: true
  },
  {
    name: 'Finance & Investissement',
    role: 'banquier',
    specialty: 'Gros projets et dÃ©veloppement',
    location: 'Marseille',
    rating: 4.7,
    reviewCount: 98,
    price: 'Sur Ã©tude',
    availability: 'Sur RDV uniquement',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=41',
    badges: ['Gros montants', 'DÃ©veloppement', 'Franchise'],
    description: 'Banque d\'affaires, financement projets d\'envergure.',
    ecoFriendly: false,
    skills: ['CrÃ©dit corporate', 'Financement franchise', 'LevÃ©e de fonds'],
    experience: '25 ans d\'expÃ©rience',
    email: 'contact@finance-invest.fr',
    phone: '04 91 33 44 55',
    featured: false
  },

  // ========== COMPTABLES (3) ==========
  {
    name: 'Expert Comptable CHR',
    role: 'comptable',
    specialty: 'ComptabilitÃ© spÃ©cialisÃ©e restauration',
    location: 'Paris 9e',
    rating: 4.9,
    reviewCount: 276,
    price: '200â‚¬/mois',
    availability: 'DÃ¨s 1er mois',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=19',
    badges: ['CertifiÃ© OEC', 'Bilan annuel', 'DÃ©clarations TVA'],
    description: 'Expert-comptable diplÃ´mÃ©, spÃ©cialiste CHR et restauration.',
    ecoFriendly: false,
    skills: ['ComptabilitÃ© CHR', 'Optimisation fiscale', 'Conseil gestion'],
    experience: '20 ans d\'expÃ©rience',
    email: 'cabinet@expert-chr.fr',
    phone: '01 47 55 88 99',
    featured: true
  },
  {
    name: 'Compta & Gestion Pro',
    role: 'comptable',
    specialty: 'ComptabilitÃ© et gestion PME',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 189,
    price: '180â‚¬/mois',
    availability: 'Engagement 12 mois',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=35',
    badges: ['Logiciel cloud', 'Tableau de bord', 'Conseil'],
    description: 'Cabinet comptable moderne, outils digitaux et accompagnement.',
    ecoFriendly: false,
    skills: ['ComptabilitÃ© cloud', 'Tableaux de bord', 'Paie'],
    experience: '15 ans d\'expÃ©rience',
    email: 'contact@compta-gestion.fr',
    phone: '04 78 66 77 88',
    featured: false
  },
  {
    name: 'FiscalitÃ© & Optimisation',
    role: 'comptable',
    specialty: 'Optimisation fiscale et sociale',
    location: 'Bordeaux',
    rating: 4.8,
    reviewCount: 145,
    price: '250â‚¬/mois',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=52',
    badges: ['Optimisation fiscale', 'Audit', 'Conseil stratÃ©gique'],
    description: 'Expert en optimisation fiscale et sociale pour restaurateurs.',
    ecoFriendly: false,
    skills: ['FiscalitÃ©', 'Optimisation charges', 'Audit comptable'],
    experience: '22 ans d\'expÃ©rience',
    email: 'expert@fiscalite-optim.fr',
    phone: '05 56 77 88 99',
    featured: true
  },

  // ========== INVESTISSEURS (3) ==========
  {
    name: 'Business Angels Restauration',
    role: 'investisseur',
    specialty: 'Investissement 50K-500Kâ‚¬',
    location: 'Paris',
    rating: 4.8,
    reviewCount: 67,
    price: 'Prise de participation',
    availability: 'Ã‰tude dossier',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=23',
    badges: ['Business Angels', 'Accompagnement', 'RÃ©seau'],
    description: 'RÃ©seau de business angels spÃ©cialisÃ©s en restauration.',
    ecoFriendly: false,
    skills: ['Financement equity', 'Accompagnement stratÃ©gique', 'RÃ©seau pros'],
    experience: '10 ans d\'expÃ©rience',
    email: 'contact@ba-restauration.fr',
    phone: '01 53 44 55 66',
    featured: true
  },
  {
    name: 'Fonds d\'Investissement Food',
    role: 'investisseur',
    specialty: 'Investissement 100K-2Mâ‚¬',
    location: 'Lyon',
    rating: 4.9,
    reviewCount: 89,
    price: 'Equity / Dette',
    availability: 'Projets structurÃ©s',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=37',
    badges: ['Fonds spÃ©cialisÃ©', 'Gros montants', 'DÃ©veloppement'],
    description: 'Fonds d\'investissement dÃ©diÃ© aux projets food innovants.',
    ecoFriendly: true,
    skills: ['Private equity', 'DÃ©veloppement', 'Franchise'],
    experience: '15 ans d\'expÃ©rience',
    email: 'invest@fonds-food.fr',
    phone: '04 72 99 00 11',
    featured: true
  },
  {
    name: 'Investisseur PrivÃ©',
    role: 'investisseur',
    specialty: 'Investissement 20K-200Kâ‚¬',
    location: 'Marseille',
    rating: 4.6,
    reviewCount: 45,
    price: 'NÃ©gociable',
    availability: 'Ã‰tude projet',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=61',
    badges: ['Investisseur privÃ©', 'Flexible', 'Accompagnement'],
    description: 'Investisseur privÃ©, financement de projets prometteurs.',
    ecoFriendly: false,
    skills: ['Financement flexible', 'Conseil opÃ©rationnel', 'Mise en relation'],
    experience: '8 ans d\'expÃ©rience',
    email: 'invest.prive@gmail.com',
    phone: '06 88 99 00 11',
    featured: false
  },

  // ========== AUDITEURS (2) ==========
  {
    name: 'Audit & ConformitÃ© Pro',
    role: 'auditeur',
    specialty: 'Audit hygiÃ¨ne et conformitÃ© HACCP',
    location: 'Paris et rÃ©gion',
    rating: 4.9,
    reviewCount: 134,
    price: '350â‚¬/audit',
    availability: 'Intervention rapide',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=16',
    badges: ['HACCP', 'Plan de maÃ®trise sanitaire', 'Formation'],
    description: 'Auditeur hygiÃ¨ne certifiÃ©, accompagnement mise en conformitÃ©.',
    ecoFriendly: false,
    skills: ['Audit HACCP', 'Formation Ã©quipe', 'Mise en conformitÃ©'],
    experience: '18 ans d\'expÃ©rience',
    email: 'audit@conformite-pro.fr',
    phone: '01 55 66 77 88',
    featured: true
  },
  {
    name: 'Consultant QualitÃ© Restauration',
    role: 'auditeur',
    specialty: 'Audit qualitÃ© et optimisation',
    location: 'Lyon et rÃ©gion',
    rating: 4.7,
    reviewCount: 98,
    price: '450â‚¬/jour',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=43',
    badges: ['ISO 22000', 'AmÃ©lioration continue', 'Audit complet'],
    description: 'Consultant qualitÃ©, audit et optimisation processus.',
    ecoFriendly: false,
    skills: ['Audit qualitÃ©', 'Certification ISO', 'AmÃ©lioration process'],
    experience: '22 ans d\'expÃ©rience',
    email: 'contact@qualite-resto.fr',
    phone: '04 78 11 22 33',
    featured: false
  },

  // ========== DEMANDEURS D'EMPLOI / CANDIDATS (5) ==========
  {
    name: 'Thomas Serveur Pro',
    role: 'candidat',
    specialty: 'Serveur expÃ©rimentÃ©, bilingue anglais',
    location: 'Paris',
    rating: 4.8,
    reviewCount: 23,
    price: '2100â‚¬ net/mois',
    availability: 'Disponible immÃ©diatement',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=14',
    badges: ['8 ans exp', 'Bilingue', 'Sommellerie niveau 1'],
    description: 'Serveur professionnel avec 8 ans d\'expÃ©rience en gastronomie.',
    ecoFriendly: false,
    skills: ['Service de salle', 'Vins', 'Anglais courant'],
    experience: '8 ans d\'expÃ©rience',
    email: 'thomas.serveur@gmail.com',
    phone: '06 12 34 56 78',
    featured: true
  },
  {
    name: 'Marie Chef de Partie',
    role: 'candidat',
    specialty: 'Chef de partie garde-manger',
    location: 'Lyon',
    rating: 4.9,
    reviewCount: 18,
    price: '2400â‚¬ net/mois',
    availability: 'PrÃ©avis 1 mois',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=32',
    badges: ['CAP Cuisine', '6 ans exp', 'Brigade Ã©toilÃ©e'],
    description: 'Chef de partie formÃ©e en brigade Ã©toilÃ©e, spÃ©cialiste entrÃ©es.',
    ecoFriendly: false,
    skills: ['Garde-manger', 'PÃ¢tisserie', 'Gestion stock'],
    experience: '6 ans d\'expÃ©rience',
    email: 'marie.cdp@gmail.com',
    phone: '06 23 45 67 89',
    featured: true
  },
  {
    name: 'Lucas Barman Mixologue',
    role: 'candidat',
    specialty: 'Barman crÃ©atif et mixologie',
    location: 'Nice',
    rating: 4.7,
    reviewCount: 34,
    price: '2200â‚¬ net/mois',
    availability: 'Disponible de suite',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=53',
    badges: ['Mixologie', 'Cocktails signature', '5 ans exp'],
    description: 'Barman crÃ©atif, spÃ©cialiste cocktails signature et bar management.',
    ecoFriendly: false,
    skills: ['Mixologie', 'Gestion bar', 'CrÃ©ation carte'],
    experience: '5 ans d\'expÃ©rience',
    email: 'lucas.barman@gmail.com',
    phone: '06 34 56 78 90',
    featured: false
  },
  {
    name: 'Sophie Commis de Cuisine',
    role: 'candidat',
    specialty: 'Commis de cuisine motivÃ©e',
    location: 'Marseille',
    rating: 4.5,
    reviewCount: 12,
    price: '1800â‚¬ net/mois',
    availability: 'ImmÃ©diate',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=65',
    badges: ['CAP Cuisine', 'MotivÃ©e', 'Formation continue'],
    description: 'Commis de cuisine CAP, motivÃ©e et dÃ©sireuse d\'apprendre.',
    ecoFriendly: false,
    skills: ['PrÃ©parations de base', 'Entretien cuisine', 'Apprentissage rapide'],
    experience: '2 ans d\'expÃ©rience',
    email: 'sophie.commis@gmail.com',
    phone: '06 45 67 89 01',
    featured: false
  },
  {
    name: 'Alexandre Plongeur Polyvalent',
    role: 'candidat',
    specialty: 'Plonge et aide cuisine',
    location: 'Toulouse',
    rating: 4.6,
    reviewCount: 28,
    price: '1700â‚¬ net/mois',
    availability: 'Disponible',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=69',
    badges: ['Polyvalent', 'Fiable', 'Horaires flexibles'],
    description: 'Plongeur sÃ©rieux et polyvalent, peut aider en prÃ©parations simples.',
    ecoFriendly: false,
    skills: ['Plonge', 'Nettoyage', 'Aide prÃ©parations'],
    experience: '3 ans d\'expÃ©rience',
    email: 'alex.plongeur@gmail.com',
    phone: '06 56 78 90 12',
    featured: false
  }
];

/**
 * Fonction principale de seed
 */
async function seedPartners() {
  try {
    logger.info('ðŸŒ± DÃ©marrage du seed des partenaires...');

    // Connexion Ã  MongoDB
    const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/restauconnect';
    await mongoose.connect(MONGODB_URI);
    logger.info('âœ… ConnectÃ© Ã  MongoDB');

    // Supprimer les anciens partenaires (optionnel - dÃ©commenter si besoin)
    // await Partner.deleteMany({});
    // logger.info('ðŸ—‘ï¸  Anciens partenaires supprimÃ©s');

    // InsÃ©rer les nouveaux partenaires
    const insertedPartners = await Partner.insertMany(partnersData);
    logger.info(`âœ… ${insertedPartners.length} partenaires insÃ©rÃ©s avec succÃ¨s !`);

    // Afficher les statistiques
    const stats = await (Partner as any).getStatsByRole();
    logger.info('\nðŸ“Š Statistiques par rÃ´le :');
    stats.forEach((stat: any) => {
      logger.info(`   ${stat._id}: ${stat.count} partenaires (${stat.verified} vÃ©rifiÃ©s, note moyenne: ${stat.avgRating.toFixed(2)})`);
    });

    logger.info('\nðŸŽ‰ Seed terminÃ© avec succÃ¨s !');
    process.exit(0);

  } catch (error: any) {
    logger.error('âŒ Erreur lors du seed:', error);
    process.exit(1);
  }
}

// Lancer le seed
seedPartners();
