/**
 * Script de seed pour les partenaires
 * InsÃƒÂ¨re les 45 partenaires mock dans la base de donnÃƒÂ©es MongoDB
 * 
 * Usage: npm run seed:partners
 * ou: ts-node src/scripts/seedPartners.ts
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import Partner from '../models/Partner';
import { logger } from '../utils/logger';

// Charger les variables d'environnement
dotenv.config({ path: path.join(__dirname, '../../.env') });

const partnersData = [
  // ========== RESTAURANTS (5) ==========
  {
    name: 'Le Bistrot Gourmand',
    role: 'restaurant',
    specialty: 'Cuisine franÃƒÂ§aise traditionnelle',
    location: 'Paris 11e',
    rating: 4.7,
    reviewCount: 342,
    price: '25-45Ã¢â€šÂ¬',
    availability: 'Ouvert 7j/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=12',
    badges: ['Bio', 'Terrasse', 'Parking'],
    description: 'Restaurant familial proposant une cuisine franÃƒÂ§aise authentique avec des produits de saison.',
    ecoFriendly: true,
    skills: ['Cuisine traditionnelle', 'Vins franÃƒÂ§ais', 'Accueil chaleureux'],
    experience: '15 ans d\'expÃƒÂ©rience',
    email: 'contact@bistrotgourmand.fr',
    phone: '01 43 55 21 89',
    featured: true
  },
  {
    name: 'La Table du Chef',
    role: 'restaurant',
    specialty: 'Gastronomie, 1 Ãƒâ€°toile Michelin',
    location: 'Lyon 2e',
    rating: 4.9,
    reviewCount: 567,
    price: '85-120Ã¢â€šÂ¬',
    availability: 'Mar-Sam midi et soir',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=33',
    badges: ['1 Ãƒâ€°toile Michelin', 'Cave exceptionnelle', 'Chef ÃƒÂ©toilÃƒÂ©'],
    description: 'Restaurant gastronomique dirigÃƒÂ© par un chef ÃƒÂ©toilÃƒÂ©, cuisine crÃƒÂ©ative et raffinÃƒÂ©e.',
    ecoFriendly: false,
    skills: ['Haute gastronomie', 'Accords mets-vins', 'Cuisine molÃƒÂ©culaire'],
    experience: '25 ans d\'expÃƒÂ©rience',
    email: 'reservation@tableduchet.fr',
    phone: '04 78 28 19 59',
    featured: true
  },
  {
    name: 'Sushi Master',
    role: 'restaurant',
    specialty: 'Cuisine japonaise authentique',
    location: 'Marseille 6e',
    rating: 4.6,
    reviewCount: 289,
    price: '30-55Ã¢â€šÂ¬',
    availability: 'Tous les jours',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=51',
    badges: ['Chef japonais', 'Poisson frais quotidien', 'Menu Omakase'],
    description: 'Restaurant japonais tenu par un chef formÃƒÂ© ÃƒÂ  Tokyo, poissons ultra-frais.',
    ecoFriendly: true,
    skills: ['Sushi', 'Sashimi', 'Cuisine kaiseki'],
    experience: '12 ans d\'expÃƒÂ©rience',
    email: 'hello@sushimaster.fr',
    phone: '04 91 33 27 88',
    featured: false
  },
  {
    name: 'Pizza Bella Napoli',
    role: 'restaurant',
    specialty: 'Pizzeria napolitaine',
    location: 'Nice',
    rating: 4.5,
    reviewCount: 423,
    price: '12-22Ã¢â€šÂ¬',
    availability: 'Midi et soir',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=68',
    badges: ['Four ÃƒÂ  bois', 'PÃƒÂ¢te maison', 'Livraison'],
    description: 'Pizzeria authentique avec four ÃƒÂ  bois, pÃƒÂ¢te pÃƒÂ©trie chaque matin.',
    ecoFriendly: false,
    skills: ['Pizza napolitaine', 'Antipasti', 'Desserts italiens'],
    experience: '8 ans d\'expÃƒÂ©rience',
    email: 'info@pizzabellanapoli.fr',
    phone: '04 93 87 45 23',
    featured: false
  },
  {
    name: 'Le VÃƒÂ©gÃƒÂ©tal',
    role: 'restaurant',
    specialty: 'Cuisine vÃƒÂ©gÃƒÂ©tarienne & vegan',
    location: 'Bordeaux',
    rating: 4.8,
    reviewCount: 198,
    price: '18-32Ã¢â€šÂ¬',
    availability: 'Lun-Sam midi et soir',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=15',
    badges: ['100% vÃƒÂ©gÃƒÂ©tal', 'Bio', 'ZÃƒÂ©ro dÃƒÂ©chet'],
    description: 'Restaurant vÃƒÂ©gÃƒÂ©talien et bio, engagement zÃƒÂ©ro dÃƒÂ©chet.',
    ecoFriendly: true,
    skills: ['Cuisine vegan', 'Produits bio', 'PÃƒÂ¢tisserie sans gluten'],
    experience: '5 ans d\'expÃƒÂ©rience',
    email: 'contact@levegetal.fr',
    phone: '05 56 44 28 91',
    featured: true
  },

  // ========== FOURNISSEURS (5) ==========
  {
    name: 'BioFresh Distribution',
    role: 'fournisseur',
    specialty: 'Fruits et lÃƒÂ©gumes bio de saison',
    location: 'Rungis',
    rating: 4.8,
    reviewCount: 156,
    price: 'Sur devis',
    availability: 'Livraison 6j/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=22',
    badges: ['Certification AB', 'Circuit court', 'FraÃƒÂ®cheur garantie'],
    description: 'Grossiste en fruits et lÃƒÂ©gumes bio, approvisionnement direct producteurs.',
    ecoFriendly: true,
    skills: ['Produits bio', 'Livraison rapide', 'Conseil technique'],
    experience: '20 ans d\'expÃƒÂ©rience',
    email: 'commercial@biofresh.fr',
    phone: '01 49 73 24 56',
    featured: true
  },
  {
    name: 'Viandes Premium',
    role: 'fournisseur',
    specialty: 'Viandes Label Rouge et races franÃƒÂ§aises',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 234,
    price: 'Sur devis',
    availability: 'Commandes J-1',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=44',
    badges: ['Label Rouge', 'Charolais', 'Limousin'],
    description: 'Grossiste en viandes de qualitÃƒÂ©, traÃƒÂ§abilitÃƒÂ© complÃƒÂ¨te de l\'ÃƒÂ©levage.',
    ecoFriendly: false,
    skills: ['DÃƒÂ©coupe professionnelle', 'Maturation', 'Conseil chef'],
    experience: '30 ans d\'expÃƒÂ©rience',
    email: 'vente@viandespremium.fr',
    phone: '04 72 85 39 67',
    featured: false
  },
  {
    name: 'Poissonnerie de la CriÃƒÂ©e',
    role: 'fournisseur',
    specialty: 'Poissons et fruits de mer ultra-frais',
    location: 'Marseille',
    rating: 4.9,
    reviewCount: 187,
    price: 'Variable selon arrivage',
    availability: 'Arrivage quotidien 6h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=58',
    badges: ['PÃƒÂªche locale', 'TraÃƒÂ§abilitÃƒÂ© MSC', 'Arrivage quotidien'],
    description: 'Poissonnerie professionnelle, approvisionnement criÃƒÂ©e locale.',
    ecoFriendly: true,
    skills: ['Poissons mÃƒÂ©diterranÃƒÂ©e', 'Coquillages', 'Conseils chef'],
    experience: '18 ans d\'expÃƒÂ©rience',
    email: 'commande@crieemarseille.fr',
    phone: '04 91 90 12 45',
    featured: true
  },
  {
    name: 'Vins & Spiritueux Prestige',
    role: 'fournisseur',
    specialty: 'Vins fins et spiritueux premium',
    location: 'Bordeaux',
    rating: 4.9,
    reviewCount: 298,
    price: 'Sur devis',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=71',
    badges: ['Grands crus', 'Sommelier conseil', 'Livraison sÃƒÂ©curisÃƒÂ©e'],
    description: 'Distributeur de vins fins et spiritueux, accompagnement sommelier.',
    ecoFriendly: false,
    skills: ['Ã…â€™nologie', 'Grands crus', 'Spiritueux rares'],
    experience: '25 ans d\'expÃƒÂ©rience',
    email: 'contact@vinsprestige.fr',
    phone: '05 56 81 23 78',
    featured: true
  },
  {
    name: 'Ãƒâ€°picerie Fine du Monde',
    role: 'fournisseur',
    specialty: 'Produits d\'ÃƒÂ©picerie fine internationaux',
    location: 'Paris 3e',
    rating: 4.6,
    reviewCount: 145,
    price: 'Sur devis',
    availability: '48h dÃƒÂ©lai',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=29',
    badges: ['Import direct', '500+ rÃƒÂ©fÃƒÂ©rences', 'Produits rares'],
    description: 'Grossiste en ÃƒÂ©picerie fine, huiles, ÃƒÂ©pices, condiments du monde.',
    ecoFriendly: false,
    skills: ['Ãƒâ€°pices rares', 'Huiles d\'exception', 'Condiments artisanaux'],
    experience: '15 ans d\'expÃƒÂ©rience',
    email: 'pro@epiceriefine.fr',
    phone: '01 42 77 88 92',
    featured: false
  },

  // ========== ARTISANS (5) ==========
  {
    name: 'Jean-Marc Plomberie',
    role: 'artisan',
    specialty: 'Plomberie, chauffage, climatisation',
    location: 'Paris',
    rating: 4.8,
    reviewCount: 167,
    price: '65Ã¢â€šÂ¬/h + dÃƒÂ©placement',
    availability: 'Urgence 24/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=11',
    badges: ['RGE', 'Urgence 24/7', 'Devis gratuit'],
    description: 'Artisan plombier spÃƒÂ©cialisÃƒÂ© en restauration commerciale.',
    ecoFriendly: false,
    skills: ['Plomberie pro', 'Lave-vaisselle industriel', 'DÃƒÂ©pannage urgent'],
    experience: '22 ans d\'expÃƒÂ©rience',
    email: 'jm.plomberie@gmail.com',
    phone: '06 12 34 56 78',
    featured: false
  },
  {
    name: 'Ãƒâ€°lectricitÃƒÂ© Pro Services',
    role: 'artisan',
    specialty: 'Installation ÃƒÂ©lectrique professionnelle',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 234,
    price: '55Ã¢â€šÂ¬/h',
    availability: 'Lun-Sam 8h-19h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=25',
    badges: ['Qualifelec', 'Normes CHR', 'Mise aux normes'],
    description: 'Ãƒâ€°lectricien spÃƒÂ©cialisÃƒÂ© en locaux commerciaux et restauration.',
    ecoFriendly: false,
    skills: ['Ãƒâ€°lectricitÃƒÂ© commerciale', 'Tableaux ÃƒÂ©lectriques', 'Mise aux normes'],
    experience: '18 ans d\'expÃƒÂ©rience',
    email: 'contact@elec-pro.fr',
    phone: '04 78 45 67 89',
    featured: false
  },
  {
    name: 'Froid Expertise',
    role: 'artisan',
    specialty: 'SpÃƒÂ©cialiste froid commercial et climatisation',
    location: 'Marseille',
    rating: 4.9,
    reviewCount: 189,
    price: '75Ã¢â€šÂ¬/h',
    availability: 'Urgence 24/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=38',
    badges: ['Fluides frigorigÃƒÂ¨nes', 'DÃƒÂ©pannage urgent', 'Contrat maintenance'],
    description: 'Expert en installation et maintenance de chambres froides.',
    ecoFriendly: true,
    skills: ['Chambres froides', 'Climatisation', 'Contrat maintenance'],
    experience: '25 ans d\'expÃƒÂ©rience',
    email: 'urgence@froid-expertise.fr',
    phone: '04 91 22 88 44',
    featured: true
  },
  {
    name: 'Menuiserie Restaurant',
    role: 'artisan',
    specialty: 'AmÃƒÂ©nagement et menuiserie sur mesure',
    location: 'Toulouse',
    rating: 4.6,
    reviewCount: 98,
    price: 'Sur devis',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=47',
    badges: ['Bois massif', 'CrÃƒÂ©ations sur mesure', 'Finitions haut de gamme'],
    description: 'Menuisier spÃƒÂ©cialisÃƒÂ© en amÃƒÂ©nagement de restaurants.',
    ecoFriendly: true,
    skills: ['Menuiserie sur mesure', 'Agencement', 'Bois nobles'],
    experience: '12 ans d\'expÃƒÂ©rience',
    email: 'atelier@menuiserie-resto.fr',
    phone: '05 61 23 45 67',
    featured: false
  },
  {
    name: 'Peinture & DÃƒÂ©coration Pro',
    role: 'artisan',
    specialty: 'Peinture et dÃƒÂ©coration locaux commerciaux',
    location: 'Nice',
    rating: 4.5,
    reviewCount: 156,
    price: '45Ã¢â€šÂ¬/h',
    availability: 'Lun-Sam',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=63',
    badges: ['Peintures ÃƒÂ©cologiques', 'DÃƒÂ©coration tendance', 'Devis rapide'],
    description: 'Artisan peintre, spÃƒÂ©cialiste rÃƒÂ©novation de restaurants.',
    ecoFriendly: true,
    skills: ['Peinture dÃƒÂ©corative', 'Enduits', 'RevÃƒÂªtements muraux'],
    experience: '10 ans d\'expÃƒÂ©rience',
    email: 'contact@peinture-deco.fr',
    phone: '04 93 56 78 90',
    featured: false
  },

  // ========== TRANSPORTEURS (3) ==========
  {
    name: 'Express Livraison Pro',
    role: 'transporteur',
    specialty: 'Livraison express en vÃƒÂ©hicules frigorifiques',
    location: 'Paris et ÃƒÅ½le-de-France',
    rating: 4.7,
    reviewCount: 432,
    price: 'Ãƒâ‚¬ partir de 25Ã¢â€šÂ¬',
    availability: '7j/7 6h-22h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=18',
    badges: ['VÃƒÂ©hicules frigo', 'Tracking temps rÃƒÂ©el', 'Livraison J+0'],
    description: 'Service de livraison professionnel pour denrÃƒÂ©es pÃƒÂ©rissables.',
    ecoFriendly: false,
    skills: ['Transport frigorifique', 'Respect chaÃƒÂ®ne du froid', 'Livraison express'],
    experience: '15 ans d\'expÃƒÂ©rience',
    email: 'dispatch@express-livraison.fr',
    phone: '01 48 22 33 44',
    featured: true
  },
  {
    name: 'Logistique Food Service',
    role: 'transporteur',
    specialty: 'Transport national denrÃƒÂ©es alimentaires',
    location: 'Couverture nationale',
    rating: 4.8,
    reviewCount: 567,
    price: 'Sur devis',
    availability: '24/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=42',
    badges: ['HACCP', 'Flotte 50 vÃƒÂ©hicules', 'Assurance marchandises'],
    description: 'Transporteur spÃƒÂ©cialisÃƒÂ© en logistique alimentaire.',
    ecoFriendly: false,
    skills: ['Transport longue distance', 'Gestion tempÃƒÂ©rature', 'Planning optimisÃƒÂ©'],
    experience: '28 ans d\'expÃƒÂ©rience',
    email: 'commercial@logistique-food.fr',
    phone: '01 60 44 55 66',
    featured: true
  },
  {
    name: 'Coursiers Ãƒâ€°cologiques',
    role: 'transporteur',
    specialty: 'Livraison urbaine en vÃƒÂ©lo cargo',
    location: 'Paris, Lyon, Marseille',
    rating: 4.6,
    reviewCount: 198,
    price: '15-30Ã¢â€šÂ¬',
    availability: 'Lun-Sam 7h-20h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=56',
    badges: ['100% vÃƒÂ©lo', 'ZÃƒÂ©ro ÃƒÂ©mission', 'Livraison 2h'],
    description: 'Coursiers ÃƒÂ  vÃƒÂ©lo pour livraisons urbaines ÃƒÂ©co-responsables.',
    ecoFriendly: true,
    skills: ['Livraison vÃƒÂ©lo', 'Respect environnement', 'RapiditÃƒÂ© urbaine'],
    experience: '5 ans d\'expÃƒÂ©rience',
    email: 'hello@coursiers-eco.fr',
    phone: '06 78 90 12 34',
    featured: false
  },

  // ========== COMMUNITY MANAGERS (3) ==========
  {
    name: 'Digital Food Expert',
    role: 'community_manager',
    specialty: 'Community management spÃƒÂ©cialisÃƒÂ© food',
    location: 'Paris (Remote)',
    rating: 4.9,
    reviewCount: 87,
    price: '550Ã¢â€šÂ¬/mois',
    availability: 'Contrat 6 mois min',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=31',
    badges: ['Instagram +100K', 'ROI prouvÃƒÂ©', 'StratÃƒÂ©gie digitale'],
    description: 'Community manager expert en food, croissance Instagram garantie.',
    ecoFriendly: false,
    skills: ['Instagram', 'TikTok', 'StratÃƒÂ©gie contenu'],
    experience: '7 ans d\'expÃƒÂ©rience',
    email: 'contact@digitalfood.fr',
    phone: '06 45 67 89 01',
    featured: true
  },
  {
    name: 'Content Creator Food',
    role: 'community_manager',
    specialty: 'CrÃƒÂ©ation de contenu photo/vidÃƒÂ©o food',
    location: 'Lyon (Remote)',
    rating: 4.7,
    reviewCount: 124,
    price: '450Ã¢â€šÂ¬/mois',
    availability: 'Freelance',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=49',
    badges: ['Photo pro', 'VidÃƒÂ©o Reels', 'Storytelling'],
    description: 'CrÃƒÂ©ateur de contenu spÃƒÂ©cialisÃƒÂ© en photographie culinaire.',
    ecoFriendly: false,
    skills: ['Photographie culinaire', 'Montage vidÃƒÂ©o', 'Copywriting'],
    experience: '5 ans d\'expÃƒÂ©rience',
    email: 'hello@contentcreator.fr',
    phone: '06 23 45 67 89',
    featured: false
  },
  {
    name: 'Social Media Manager Pro',
    role: 'community_manager',
    specialty: 'Gestion complÃƒÂ¨te rÃƒÂ©seaux sociaux',
    location: 'Remote',
    rating: 4.8,
    reviewCount: 156,
    price: '650Ã¢â€šÂ¬/mois',
    availability: 'Temps plein',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=64',
    badges: ['Multi-plateformes', 'Analytics', 'PublicitÃƒÂ©s Meta'],
    description: 'Social media manager certifiÃƒÂ©, gestion complÃƒÂ¨te prÃƒÂ©sence digitale.',
    ecoFriendly: false,
    skills: ['Meta Ads', 'Google Analytics', 'StratÃƒÂ©gie multi-canal'],
    experience: '9 ans d\'expÃƒÂ©rience',
    email: 'pro@socialmedia.fr',
    phone: '06 78 12 34 56',
    featured: true
  },

  // ========== BANQUIERS (3) ==========
  {
    name: 'CrÃƒÂ©dit Pro Restauration',
    role: 'banquier',
    specialty: 'Financement professionnel CHR',
    location: 'Paris 8e',
    rating: 4.6,
    reviewCount: 234,
    price: 'Consultation gratuite',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=13',
    badges: ['SpÃƒÂ©cialiste CHR', 'Taux prÃƒÂ©fÃƒÂ©rentiels', 'Accompagnement'],
    description: 'Conseiller bancaire spÃƒÂ©cialisÃƒÂ© en financement restauration.',
    ecoFriendly: false,
    skills: ['CrÃƒÂ©dit professionnel', 'Leasing ÃƒÂ©quipement', 'TrÃƒÂ©sorerie'],
    experience: '18 ans d\'expÃƒÂ©rience',
    email: 'conseil@creditpro.fr',
    phone: '01 44 55 66 77',
    featured: true
  },
  {
    name: 'Banque des Entrepreneurs',
    role: 'banquier',
    specialty: 'Accompagnement start-up food',
    location: 'Lyon',
    rating: 4.8,
    reviewCount: 167,
    price: 'RDV gratuit',
    availability: 'Lun-Ven 9h-18h',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=27',
    badges: ['Start-up friendly', 'PrÃƒÂªt d\'honneur', 'MicrocrÃƒÂ©dit'],
    description: 'Banque spÃƒÂ©cialisÃƒÂ©e dans l\'accompagnement de jeunes entrepreneurs.',
    ecoFriendly: true,
    skills: ['Financement innovation', 'PrÃƒÂªt BPI', 'Accompagnement'],
    experience: '12 ans d\'expÃƒÂ©rience',
    email: 'startup@banque-entrepreneurs.fr',
    phone: '04 72 88 99 00',
    featured: true
  },
  {
    name: 'Finance & Investissement',
    role: 'banquier',
    specialty: 'Gros projets et dÃƒÂ©veloppement',
    location: 'Marseille',
    rating: 4.7,
    reviewCount: 98,
    price: 'Sur ÃƒÂ©tude',
    availability: 'Sur RDV uniquement',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=41',
    badges: ['Gros montants', 'DÃƒÂ©veloppement', 'Franchise'],
    description: 'Banque d\'affaires, financement projets d\'envergure.',
    ecoFriendly: false,
    skills: ['CrÃƒÂ©dit corporate', 'Financement franchise', 'LevÃƒÂ©e de fonds'],
    experience: '25 ans d\'expÃƒÂ©rience',
    email: 'contact@finance-invest.fr',
    phone: '04 91 33 44 55',
    featured: false
  },

  // ========== COMPTABLES (3) ==========
  {
    name: 'Expert Comptable CHR',
    role: 'comptable',
    specialty: 'ComptabilitÃƒÂ© spÃƒÂ©cialisÃƒÂ©e restauration',
    location: 'Paris 9e',
    rating: 4.9,
    reviewCount: 276,
    price: '200Ã¢â€šÂ¬/mois',
    availability: 'DÃƒÂ¨s 1er mois',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=19',
    badges: ['CertifiÃƒÂ© OEC', 'Bilan annuel', 'DÃƒÂ©clarations TVA'],
    description: 'Expert-comptable diplÃƒÂ´mÃƒÂ©, spÃƒÂ©cialiste CHR et restauration.',
    ecoFriendly: false,
    skills: ['ComptabilitÃƒÂ© CHR', 'Optimisation fiscale', 'Conseil gestion'],
    experience: '20 ans d\'expÃƒÂ©rience',
    email: 'cabinet@expert-chr.fr',
    phone: '01 47 55 88 99',
    featured: true
  },
  {
    name: 'Compta & Gestion Pro',
    role: 'comptable',
    specialty: 'ComptabilitÃƒÂ© et gestion PME',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 189,
    price: '180Ã¢â€šÂ¬/mois',
    availability: 'Engagement 12 mois',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=35',
    badges: ['Logiciel cloud', 'Tableau de bord', 'Conseil'],
    description: 'Cabinet comptable moderne, outils digitaux et accompagnement.',
    ecoFriendly: false,
    skills: ['ComptabilitÃƒÂ© cloud', 'Tableaux de bord', 'Paie'],
    experience: '15 ans d\'expÃƒÂ©rience',
    email: 'contact@compta-gestion.fr',
    phone: '04 78 66 77 88',
    featured: false
  },
  {
    name: 'FiscalitÃƒÂ© & Optimisation',
    role: 'comptable',
    specialty: 'Optimisation fiscale et sociale',
    location: 'Bordeaux',
    rating: 4.8,
    reviewCount: 145,
    price: '250Ã¢â€šÂ¬/mois',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=52',
    badges: ['Optimisation fiscale', 'Audit', 'Conseil stratÃƒÂ©gique'],
    description: 'Expert en optimisation fiscale et sociale pour restaurateurs.',
    ecoFriendly: false,
    skills: ['FiscalitÃƒÂ©', 'Optimisation charges', 'Audit comptable'],
    experience: '22 ans d\'expÃƒÂ©rience',
    email: 'expert@fiscalite-optim.fr',
    phone: '05 56 77 88 99',
    featured: true
  },

  // ========== INVESTISSEURS (3) ==========
  {
    name: 'Business Angels Restauration',
    role: 'investisseur',
    specialty: 'Investissement 50K-500KÃ¢â€šÂ¬',
    location: 'Paris',
    rating: 4.8,
    reviewCount: 67,
    price: 'Prise de participation',
    availability: 'Ãƒâ€°tude dossier',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=23',
    badges: ['Business Angels', 'Accompagnement', 'RÃƒÂ©seau'],
    description: 'RÃƒÂ©seau de business angels spÃƒÂ©cialisÃƒÂ©s en restauration.',
    ecoFriendly: false,
    skills: ['Financement equity', 'Accompagnement stratÃƒÂ©gique', 'RÃƒÂ©seau pros'],
    experience: '10 ans d\'expÃƒÂ©rience',
    email: 'contact@ba-restauration.fr',
    phone: '01 53 44 55 66',
    featured: true
  },
  {
    name: 'Fonds d\'Investissement Food',
    role: 'investisseur',
    specialty: 'Investissement 100K-2MÃ¢â€šÂ¬',
    location: 'Lyon',
    rating: 4.9,
    reviewCount: 89,
    price: 'Equity / Dette',
    availability: 'Projets structurÃƒÂ©s',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=37',
    badges: ['Fonds spÃƒÂ©cialisÃƒÂ©', 'Gros montants', 'DÃƒÂ©veloppement'],
    description: 'Fonds d\'investissement dÃƒÂ©diÃƒÂ© aux projets food innovants.',
    ecoFriendly: true,
    skills: ['Private equity', 'DÃƒÂ©veloppement', 'Franchise'],
    experience: '15 ans d\'expÃƒÂ©rience',
    email: 'invest@fonds-food.fr',
    phone: '04 72 99 00 11',
    featured: true
  },
  {
    name: 'Investisseur PrivÃƒÂ©',
    role: 'investisseur',
    specialty: 'Investissement 20K-200KÃ¢â€šÂ¬',
    location: 'Marseille',
    rating: 4.6,
    reviewCount: 45,
    price: 'NÃƒÂ©gociable',
    availability: 'Ãƒâ€°tude projet',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=61',
    badges: ['Investisseur privÃƒÂ©', 'Flexible', 'Accompagnement'],
    description: 'Investisseur privÃƒÂ©, financement de projets prometteurs.',
    ecoFriendly: false,
    skills: ['Financement flexible', 'Conseil opÃƒÂ©rationnel', 'Mise en relation'],
    experience: '8 ans d\'expÃƒÂ©rience',
    email: 'invest.prive@gmail.com',
    phone: '06 88 99 00 11',
    featured: false
  },

  // ========== AUDITEURS (2) ==========
  {
    name: 'Audit & ConformitÃƒÂ© Pro',
    role: 'auditeur',
    specialty: 'Audit hygiÃƒÂ¨ne et conformitÃƒÂ© HACCP',
    location: 'Paris et rÃƒÂ©gion',
    rating: 4.9,
    reviewCount: 134,
    price: '350Ã¢â€šÂ¬/audit',
    availability: 'Intervention rapide',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=16',
    badges: ['HACCP', 'Plan de maÃƒÂ®trise sanitaire', 'Formation'],
    description: 'Auditeur hygiÃƒÂ¨ne certifiÃƒÂ©, accompagnement mise en conformitÃƒÂ©.',
    ecoFriendly: false,
    skills: ['Audit HACCP', 'Formation ÃƒÂ©quipe', 'Mise en conformitÃƒÂ©'],
    experience: '18 ans d\'expÃƒÂ©rience',
    email: 'audit@conformite-pro.fr',
    phone: '01 55 66 77 88',
    featured: true
  },
  {
    name: 'Consultant QualitÃƒÂ© Restauration',
    role: 'auditeur',
    specialty: 'Audit qualitÃƒÂ© et optimisation',
    location: 'Lyon et rÃƒÂ©gion',
    rating: 4.7,
    reviewCount: 98,
    price: '450Ã¢â€šÂ¬/jour',
    availability: 'Sur RDV',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=43',
    badges: ['ISO 22000', 'AmÃƒÂ©lioration continue', 'Audit complet'],
    description: 'Consultant qualitÃƒÂ©, audit et optimisation processus.',
    ecoFriendly: false,
    skills: ['Audit qualitÃƒÂ©', 'Certification ISO', 'AmÃƒÂ©lioration process'],
    experience: '22 ans d\'expÃƒÂ©rience',
    email: 'contact@qualite-resto.fr',
    phone: '04 78 11 22 33',
    featured: false
  },

  // ========== DEMANDEURS D'EMPLOI / CANDIDATS (5) ==========
  {
    name: 'Thomas Serveur Pro',
    role: 'candidat',
    specialty: 'Serveur expÃƒÂ©rimentÃƒÂ©, bilingue anglais',
    location: 'Paris',
    rating: 4.8,
    reviewCount: 23,
    price: '2100Ã¢â€šÂ¬ net/mois',
    availability: 'Disponible immÃƒÂ©diatement',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=14',
    badges: ['8 ans exp', 'Bilingue', 'Sommellerie niveau 1'],
    description: 'Serveur professionnel avec 8 ans d\'expÃƒÂ©rience en gastronomie.',
    ecoFriendly: false,
    skills: ['Service de salle', 'Vins', 'Anglais courant'],
    experience: '8 ans d\'expÃƒÂ©rience',
    email: 'thomas.serveur@gmail.com',
    phone: '06 12 34 56 78',
    featured: true
  },
  {
    name: 'Marie Chef de Partie',
    role: 'candidat',
    specialty: 'Chef de partie garde-manger',
    location: 'Lyon',
    rating: 4.9,
    reviewCount: 18,
    price: '2400Ã¢â€šÂ¬ net/mois',
    availability: 'PrÃƒÂ©avis 1 mois',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=32',
    badges: ['CAP Cuisine', '6 ans exp', 'Brigade ÃƒÂ©toilÃƒÂ©e'],
    description: 'Chef de partie formÃƒÂ©e en brigade ÃƒÂ©toilÃƒÂ©e, spÃƒÂ©cialiste entrÃƒÂ©es.',
    ecoFriendly: false,
    skills: ['Garde-manger', 'PÃƒÂ¢tisserie', 'Gestion stock'],
    experience: '6 ans d\'expÃƒÂ©rience',
    email: 'marie.cdp@gmail.com',
    phone: '06 23 45 67 89',
    featured: true
  },
  {
    name: 'Lucas Barman Mixologue',
    role: 'candidat',
    specialty: 'Barman crÃƒÂ©atif et mixologie',
    location: 'Nice',
    rating: 4.7,
    reviewCount: 34,
    price: '2200Ã¢â€šÂ¬ net/mois',
    availability: 'Disponible de suite',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=53',
    badges: ['Mixologie', 'Cocktails signature', '5 ans exp'],
    description: 'Barman crÃƒÂ©atif, spÃƒÂ©cialiste cocktails signature et bar management.',
    ecoFriendly: false,
    skills: ['Mixologie', 'Gestion bar', 'CrÃƒÂ©ation carte'],
    experience: '5 ans d\'expÃƒÂ©rience',
    email: 'lucas.barman@gmail.com',
    phone: '06 34 56 78 90',
    featured: false
  },
  {
    name: 'Sophie Commis de Cuisine',
    role: 'candidat',
    specialty: 'Commis de cuisine motivÃƒÂ©e',
    location: 'Marseille',
    rating: 4.5,
    reviewCount: 12,
    price: '1800Ã¢â€šÂ¬ net/mois',
    availability: 'ImmÃƒÂ©diate',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=65',
    badges: ['CAP Cuisine', 'MotivÃƒÂ©e', 'Formation continue'],
    description: 'Commis de cuisine CAP, motivÃƒÂ©e et dÃƒÂ©sireuse d\'apprendre.',
    ecoFriendly: false,
    skills: ['PrÃƒÂ©parations de base', 'Entretien cuisine', 'Apprentissage rapide'],
    experience: '2 ans d\'expÃƒÂ©rience',
    email: 'sophie.commis@gmail.com',
    phone: '06 45 67 89 01',
    featured: false
  },
  {
    name: 'Alexandre Plongeur Polyvalent',
    role: 'candidat',
    specialty: 'Plonge et aide cuisine',
    location: 'Toulouse',
    rating: 4.6,
    reviewCount: 28,
    price: '1700Ã¢â€šÂ¬ net/mois',
    availability: 'Disponible',
    verified: true,
    avatar: 'https://i.pravatar.cc/300?img=69',
    badges: ['Polyvalent', 'Fiable', 'Horaires flexibles'],
    description: 'Plongeur sÃƒÂ©rieux et polyvalent, peut aider en prÃƒÂ©parations simples.',
    ecoFriendly: false,
    skills: ['Plonge', 'Nettoyage', 'Aide prÃƒÂ©parations'],
    experience: '3 ans d\'expÃƒÂ©rience',
    email: 'alex.plongeur@gmail.com',
    phone: '06 56 78 90 12',
    featured: false
  }
];

/**
 * Fonction principale de seed
 */
async function seedPartners() {
  try {
    logger.info('Ã°Å¸Å’Â± DÃƒÂ©marrage du seed des partenaires...');

    // Connexion ÃƒÂ  MongoDB
    const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/restauconnect';
    await mongoose.connect(MONGODB_URI);
    logger.info('Ã¢Å“â€¦ ConnectÃƒÂ© ÃƒÂ  MongoDB');

    // Supprimer les anciens partenaires (optionnel - dÃƒÂ©commenter si besoin)
    // await Partner.deleteMany({});
    // logger.info('Ã°Å¸â€”â€˜Ã¯Â¸Â  Anciens partenaires supprimÃƒÂ©s');

    // InsÃƒÂ©rer les nouveaux partenaires
    const insertedPartners = await Partner.insertMany(partnersData);
    logger.info(`Ã¢Å“â€¦ ${insertedPartners.length} partenaires insÃƒÂ©rÃƒÂ©s avec succÃƒÂ¨s !`);

    // Afficher les statistiques
    const stats = await (Partner as any).getStatsByRole();
    logger.info('\nÃ°Å¸â€œÅ  Statistiques par rÃƒÂ´le :');
    stats.forEach((stat: any) => {
      logger.info(`   ${stat._id}: ${stat.count} partenaires (${stat.verified} vÃƒÂ©rifiÃƒÂ©s, note moyenne: ${stat.avgRating.toFixed(2)})`);
    });

    logger.info('\nÃ°Å¸Å½â€° Seed terminÃƒÂ© avec succÃƒÂ¨s !');
    process.exit(0);

  } catch (error: any) {
    logger.error('Ã¢ÂÅ’ Erreur lors du seed:', error);
    process.exit(1);
  }
}

// Lancer le seed
seedPartners();
